# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_submiter.ui'
#
# Created: Wed Oct 12 18:23:38 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(750, 411)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(600, 200))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Form.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.gb1 = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb1.sizePolicy().hasHeightForWidth())
        self.gb1.setSizePolicy(sizePolicy)
        self.gb1.setBaseSize(QtCore.QSize(0, 0))
        self.gb1.setTitle("")
        self.gb1.setObjectName("gb1")
        self.horizontalLayout = QtGui.QHBoxLayout(self.gb1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblName = QtGui.QLabel(self.gb1)
        self.lblName.setObjectName("lblName")
        self.horizontalLayout.addWidget(self.lblName)
        self.txtSceneName = QtGui.QLineEdit(self.gb1)
        self.txtSceneName.setAutoFillBackground(False)
        self.txtSceneName.setObjectName("txtSceneName")
        self.horizontalLayout.addWidget(self.txtSceneName)
        self.gridLayout.addWidget(self.gb1, 0, 0, 1, 1)
        self.logList = QtGui.QListView(Form)
        self.logList.setMinimumSize(QtCore.QSize(0, 10))
        self.logList.setMaximumSize(QtCore.QSize(16777215, 210))
        self.logList.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.logList.setObjectName("logList")
        self.gridLayout.addWidget(self.logList, 2, 0, 1, 1)
        self.gb2 = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb2.sizePolicy().hasHeightForWidth())
        self.gb2.setSizePolicy(sizePolicy)
        self.gb2.setTitle("")
        self.gb2.setObjectName("gb2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.gb2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chkAutoDownload = QtGui.QCheckBox(self.gb2)
        self.chkAutoDownload.setChecked(True)
        self.chkAutoDownload.setObjectName("chkAutoDownload")
        self.horizontalLayout_3.addWidget(self.chkAutoDownload)
        self.chkIgnoreWarning = QtGui.QCheckBox(self.gb2)
        self.chkIgnoreWarning.setChecked(True)
        self.chkIgnoreWarning.setObjectName("chkIgnoreWarning")
        self.horizontalLayout_3.addWidget(self.chkIgnoreWarning)
        self.chkContinue = QtGui.QCheckBox(self.gb2)
        self.chkContinue.setChecked(True)
        self.chkContinue.setObjectName("chkContinue")
        self.horizontalLayout_3.addWidget(self.chkContinue)
        self.btnCheck = QtGui.QPushButton(self.gb2)
        self.btnCheck.setObjectName("btnCheck")
        self.horizontalLayout_3.addWidget(self.btnCheck)
        self.btnSubmit = QtGui.QPushButton(self.gb2)
        self.btnSubmit.setDefault(True)
        self.btnSubmit.setObjectName("btnSubmit")
        self.horizontalLayout_3.addWidget(self.btnSubmit)
        self.gridLayout.addWidget(self.gb2, 3, 0, 1, 1)
        self.taskTable = QtGui.QTableWidget(Form)
        self.taskTable.setMinimumSize(QtCore.QSize(0, 60))
        self.taskTable.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.taskTable.setAutoFillBackground(False)
        self.taskTable.setAlternatingRowColors(True)
        self.taskTable.setShowGrid(True)
        self.taskTable.setGridStyle(QtCore.Qt.SolidLine)
        self.taskTable.setRowCount(10)
        self.taskTable.setColumnCount(6)
        self.taskTable.setObjectName("taskTable")
        self.taskTable.setColumnCount(6)
        self.taskTable.setRowCount(10)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(5, item)
        self.taskTable.horizontalHeader().setVisible(True)
        self.taskTable.horizontalHeader().setCascadingSectionResizes(True)
        self.taskTable.horizontalHeader().setDefaultSectionSize(100)
        self.taskTable.horizontalHeader().setHighlightSections(True)
        self.taskTable.horizontalHeader().setSortIndicatorShown(True)
        self.taskTable.horizontalHeader().setStretchLastSection(True)
        self.taskTable.verticalHeader().setVisible(False)
        self.taskTable.verticalHeader().setHighlightSections(False)
        self.gridLayout.addWidget(self.taskTable, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.btnCheck, self.btnSubmit)
        Form.setTabOrder(self.btnSubmit, self.txtSceneName)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "HPRender", None, QtGui.QApplication.UnicodeUTF8))
        Form.setWhatsThis(QtGui.QApplication.translate("Form", "<html><head/><body><p>HPRender for Houdini submiter</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblName.setText(QtGui.QApplication.translate("Form", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtSceneName.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>提交名称(默认为文件名,可以根据需要修改)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.logList.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>检查结果(红色:错误, 黄色:警告, 绿色:通过, 双击尝试修复错误)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.chkAutoDownload.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>自动下载渲染结果(客户端开着时)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.chkAutoDownload.setText(QtGui.QApplication.translate("Form", "AutoDownload", None, QtGui.QApplication.UnicodeUTF8))
        self.chkIgnoreWarning.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>忽略警告(黄色)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.chkIgnoreWarning.setText(QtGui.QApplication.translate("Form", "IgnoreWarning", None, QtGui.QApplication.UnicodeUTF8))
        self.chkContinue.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>预渲染完成10分钟后继续渲染剩余帧</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.chkContinue.setText(QtGui.QApplication.translate("Form", "Continue after 10 mins", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCheck.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>检查,刷新</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCheck.setText(QtGui.QApplication.translate("Form", "Check / Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSubmit.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>提交</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSubmit.setText(QtGui.QApplication.translate("Form", "S U B M I T", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>可用任务列表</p><p>右键可全选或反选</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.setSortingEnabled(False)
        self.taskTable.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "ROP", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "Output", None, QtGui.QApplication.UnicodeUTF8))

